trigger:
  - dev

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: Test
        displayName: Test job
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: FlutterInstall@0
            displayName: Install Flutter
            inputs:
              channel: stable
              version: latest

          - task: FlutterTest@0
            displayName: Flutter Test
            inputs:
              projectDirectory: '.'
