# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: FlutterInstall@0
      displayName: Install Flutter
      inputs:
        channel: stable
        version: latest
    
    - task: FlutterTest@0
      displayName: Flutter Test
      inputs:
        projectDirectory: '.'
